apiVersion: v1
kind: Service
metadata:
  name: halcyon-ebpf-monitor
  namespace: observability
  labels:
    app.kubernetes.io/name: halcyon-ebpf-monitor
    app.kubernetes.io/version: "0.3.0"
spec:
  selector:
    app.kubernetes.io/name: halcyon-ebpf-monitor
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: http
      protocol: TCP
  type: ClusterIP
